export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const FILTER_PRODUCT_REQUEST = 'FILTER_PRODUCT_REQUEST';
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const CLEAR_FILTER  = 'CLEAR_FILTER ';